// In this header, you should import all the public headers of your framework using statements like #import <PhaseJump/PublicHeader.h>
#include <PhaseJump/Agent.h>
#include <PhaseJump/AgentGroup.h>
#include <PhaseJump/AgentSystem.h>
#include <PhaseJump/CycleHueEffect.h>
#include <PhaseJump/AnimatedSpriteRenderer.h>
#include <PhaseJump/AudioStreamPlayer.h>
#include <PhaseJump/AtlasTexture.h>
#include <PhaseJump/Base.h>
#include <PhaseJump/BatchByMaterialRenderProcessor.h>
#include <PhaseJump/BezierPath.h>
#include <PhaseJump/BezierPathLayout.h>
#include <PhaseJump/BlinkEffect.h>
#include <PhaseJump/EditorImGuiCommandHistoryPainter.h>
#include <PhaseJump/EditorImGuiInspectorWindowPainter.h>
#include <PhaseJump/EditorImGuiPrefabsPainter.h>
#include <PhaseJump/EditorImGuiRenderEnginePainter.h>
#include <PhaseJump/EditorImGuiResourcesPainter.h>
#include <PhaseJump/EditorImGuiScenesPainter.h>
#include <PhaseJump/EditorImGuiSceneTreePainter.h>
#include <PhaseJump/EditorImGuiWorldInfoPainter.h>
#include <PhaseJump/EditorTypes.h>
#include <PhaseJump/EditorWorldSystem.h>
#include <PhaseJump/EmitFuncs.h>
#include <PhaseJump/ButtonControl.h>
#include <PhaseJump/CapsuleMeshBuilder.h>
#include <PhaseJump/CameraCullRenderProcessor.h>
#include <PhaseJump/CenterPolyFrameMeshBuilder.h>
#include <PhaseJump/CenterPolyBuilder.h>
#include <PhaseJump/CharacterController.h>
#include <PhaseJump/CirclePathLayout2D.h>
#include <PhaseJump/CirclePositioner2D.h>
#include <PhaseJump/Class.h>
#include <PhaseJump/ClassRegistry.h>
#include <PhaseJump/ColorRenderer.h>
#include <PhaseJump/Colliders2D.h>
#include <PhaseJump/ColorView.h>
#include <PhaseJump/Command.h>
#include <PhaseJump/CommandHistory.h>
#include <PhaseJump/DepthFirstOrderRenderProcessor.h>
#include <PhaseJump/DesignSystem.h>
#include <PhaseJump/DirectionKSteering2D.h>
#include <PhaseJump/DragHandler2D.h>
#include <PhaseJump/DropFilesUIEvent.h>
#include <PhaseJump/DuckDesignSystem.h>
#include <PhaseJump/EllipseMeshBuilder.h>
#include <PhaseJump/Emitter.h>

#include <PhaseJump/FileManager.h>
#include <PhaseJump/FilePath.h>
#include <PhaseJump/FilesProcessor.h>
#include <PhaseJump/Font.h>
#include <PhaseJump/Funcs.h>

#include <PhaseJump/GLRenderEngine.h>
#include <PhaseJump/GLShaderProgram.h>
#include <PhaseJump/GLShaderProgramLoader.h>
#include <PhaseJump/GLTexture.h>
#include <PhaseJump/GLTextureBuffer.h>
#include <PhaseJump/GridMeshBuilder.h>

#include <PhaseJump/HFlow.h>
#include <PhaseJump/ImGuiMainMenuBarPainter.h>
#include <PhaseJump/ImGuiGLRenderProcessor.h>
#include <PhaseJump/ImGuiPlanPainter.h>
#include <PhaseJump/ImRenderer.h>
#include <PhaseJump/IncludeAliasFileProcessor.h>
#include <PhaseJump/Input.h>
#include <PhaseJump/InputMap.h>
#include <PhaseJump/Dev.h>
#include <PhaseJump/LimiterDriver.h>
#include <PhaseJump/Matrix.h>
#include <PhaseJump/MatrixBoard.h>
#include <PhaseJump/MatrixBoardView.h>
#include <PhaseJump/MatrixPieceHandler.h>
#include <PhaseJump/Menu.h>
#include <PhaseJump/MeshRenderer.h>
#include <PhaseJump/OrderRenderProcessor.h>
#include <PhaseJump/OverrideFeaturesRenderProcessor.h>

#include <PhaseJump/PolyFrameMeshBuilder.h>
#include <PhaseJump/RectPositioner2D.h>
#include <PhaseJump/AnimateFuncs.h>
#include <PhaseJump/QuickBehavior.h>
#include <PhaseJump/QuickBuild.h>
#include <PhaseJump/QuickCharacter.h>
#include <PhaseJump/QuickTimeline.h>
#include <PhaseJump/FramePlayable.h>
#include <PhaseJump/RenderFeature.h>
#include <PhaseJump/RenderMaterial.h>
#include <PhaseJump/RenderModel.h>
#include <PhaseJump/RenderModelBuilder.h>
#include <PhaseJump/RenderWorldSystem.h>
#include <PhaseJump/ResourceRepository.h>
#include <PhaseJump/ResourceScanner.h>
#include <PhaseJump/RoundCornersMeshBuilder.h>
#include <PhaseJump/Macros.h>
#include <PhaseJump/PageView.h>
#include <PhaseJump/PointerClickUIEvent.h>
#include <PhaseJump/Shared.h>
#include <PhaseJump/SharedVector.h>
#include <PhaseJump/SQLDatabase.h>
#include <PhaseJump/SDLAudioStream.h>
#include <PhaseJump/SDLFileManager.h>
#include <PhaseJump/SDLGLRenderContext.h>
#include <PhaseJump/SDLLoadAudioStreamOperation.h>
#include <PhaseJump/SDLLoadGLTextureOperation.h>
#include <PhaseJump/SDLLoadSDLTextureOperation.h>
#include <PhaseJump/SDLMouseDevice.h>
#include <PhaseJump/SDLPlatformClass.h>
#include <PhaseJump/SDLPlatformConfig.h>
#include <PhaseJump/SDLPlatformWindow.h>
#include <PhaseJump/SDLUIEventPoller.h>
#include <PhaseJump/SDLWorld.h>
#include <PhaseJump/Scene.h>
#include <PhaseJump/ScrollBarControl.h>
#include <PhaseJump/SignalTypes.h>
#include <PhaseJump/SimpleRaycaster2D.h>
#include <PhaseJump/Slice3TextureRenderer.h>
#include <PhaseJump/Slice9TextureRenderer.h>
#include <PhaseJump/SliderControl.h>
#include <PhaseJump/SomeControllerUIEvent.h>
#include <PhaseJump/SomeDragHandler.h>
#include <PhaseJump/SomePointerUIEvent.h>
#include <PhaseJump/SomeRenderCommandModel.h>
#include <PhaseJump/SomeRenderEngine.h>
#include <PhaseJump/SomeUIEvent.h>
#include <PhaseJump/SpriteRenderer.h>
#include <PhaseJump/StandardLoadResourcesModel.h>
#include <PhaseJump/StandardRandom.h>
#include <PhaseJump/StringUtils.h>
#include <PhaseJump/Theme.h>
#include <PhaseJump/ToggleButtonControl.h>
#include <PhaseJump/TypeClass.h>
#include <PhaseJump/UIPlan.h>
#include <PhaseJump/UIPlanner.h>
#include <PhaseJump/UIWorldSystem.h>
#include <PhaseJump/Utils.h>
#include <PhaseJump/QuadMeshBuilder.h>
#include <PhaseJump/QuadFrameMeshBuilder.h>
#include <PhaseJump/RotateKSteering2D.h>
#include <PhaseJump/ShowBoundsRenderProcessor.h>
#include <PhaseJump/ShowCollidersRenderProcessor.h>
#include <PhaseJump/ShowMeshRenderProcessor.h>
#include <PhaseJump/SimpleAnimationController.h>
#include <PhaseJump/SimpleGradientRenderer.h>
#include <PhaseJump/SomeDragGestureHandler2D.h>
#include <PhaseJump/SomeDropTarget.h>
#include <PhaseJump/SomeHoverGestureHandler.h>
#include <PhaseJump/SomeUIEvent.h>
#include <PhaseJump/StandardCore.h>
#include <PhaseJump/TextureAtlas.h>
#include <PhaseJump/TextRenderer.h>
#include <PhaseJump/VelocityKSteering.h>
#include <PhaseJump/VelocityTracker.h>
#include <PhaseJump/View2D.h>
#include <PhaseJump/PadViewLayout.h>
#include <PhaseJump/FlowStackViewLayout.h>
#include <PhaseJump/LayoutInsets.h>
#include <PhaseJump/Void.h>
#include <PhaseJump/VFlow.h>
#include <PhaseJump/WorldComponent.h>
#include <PhaseJump/ZQuad.h>

// MARK: - imGui Headers
#include <PhaseJump/imgui.h>
#include <PhaseJump/imgui_impl_sdl3.h>
#include <PhaseJump/imgui_impl_opengl3.h>
